import React from 'react';
import { useNavigate } from 'react-router-dom';
import './LegalPage.css';

const TermsPage = () => {
  const navigate = useNavigate();

  return (
    <div className="legal-page">
      <div className="g-bg"></div>
      
      <div className="legal-page__container">
        <div className="legal-page__card">
          <header className="legal-page__header">
            <h1 className="legal-page__title">Terms of <span className="g-gradient">Service</span></h1>
            <div className="login__logo-wrapper" style={{ transform: 'scale(0.8)' }}>
              <svg width="32" height="32" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M12 2L14.85 8.65L22 9.27L16.5 13.97L18.18 21L12 17.27L5.82 21L7.5 13.97L2 9.27L9.15 8.65L12 2Z" fill="url(#logo-grad-terms)" />
                <defs>
                  <linearGradient id="logo-grad-terms" x1="2" y1="2" x2="22" y2="22" gradientUnits="userSpaceOnUse">
                    <stop stopColor="#8b5cf6" />
                    <stop offset="1" stopColor="#3b82f6" />
                  </linearGradient>
                </defs>
              </svg>
            </div>
          </header>

          <div className="legal-page__body">
            <h2>1. Agreement to Terms</h2>
            <p>
              By accessing or using Growcial OS, you agree to be bound by these Terms of Service 
              and all applicable laws and regulations. If you do not agree with any of these 
              terms, you are prohibited from using or accessing this site.
            </p>

            <h2>2. Use License</h2>
            <p>
              Permission is granted to temporarily use the features of Growcial OS for personal 
              or business social media management purposes. This is the grant of a license, 
              not a transfer of title, and under this license you may not:
            </p>
            <ul>
              <li>Modify or copy the materials or AI models.</li>
              <li>Use the materials for any commercial purpose without an active subscription.</li>
              <li>Attempt to decompile or reverse engineer any software contained in Growcial OS.</li>
              <li>Remove any copyright or other proprietary notations from the materials.</li>
            </ul>

            <h2>3. Disclaimer</h2>
            <p>
              The materials on Growcial OS are provided on an 'as is' basis. Growcial OS makes no 
              warranties, expressed or implied, and hereby disclaims and negates all other 
              warranties including, without limitation, implied warranties or conditions of 
              merchantability, fitness for a particular purpose, or non-infringement of 
              intellectual property or other violation of rights.
            </p>

            <h2>4. Limitations</h2>
            <p>
              In no event shall Growcial OS or its suppliers be liable for any damages 
              (including, without limitation, damages for loss of data or profit, or due to 
              business interruption) arising out of the use or inability to use the Growcial OS 
              platform.
            </p>

            <h2>5. Social Media Platform Integration</h2>
            <p>
              Growcial OS interfaces with various social media platforms (Instagram, Facebook, 
              Twitter, YouTube). Your use of those services is subject to their respective 
              Terms of Service and Privacy Policies. Growcial OS is not responsible for 
              any actions taken by these platforms against your account.
            </p>

            <h2>6. AI Content Generation</h2>
            <p>
              Content generated by the Growcial OS AI engine is for guidance and inspiration. 
              Users are responsible for reviewing and verifying all AI-generated content 
              before publication to ensure it complies with social media platform guidelines 
              and applicable laws.
            </p>

            <h2>7. Governing Law</h2>
            <p>
              These terms and conditions are governed by and construed in accordance with the 
              laws of the jurisdiction in which the company operates and you irrevocably 
              submit to the exclusive jurisdiction of the courts in that State or location.
            </p>
          </div>

          <footer className="legal-page__footer">
            <button className="legal-page__back-btn" onClick={() => navigate('/login')}>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <line x1="19" y1="12" x2="5" y2="12"></line>
                <polyline points="12 19 5 12 12 5"></polyline>
              </svg>
              Back to Login
            </button>
            <span className="legal-page__last-updated">Last Updated: April 18, 2026</span>
          </footer>
        </div>
      </div>
    </div>
  );
};

export default TermsPage;
