import dotenv from 'dotenv';

dotenv.config();

const TELEGRAM_API_BASE = `https://api.telegram.org/bot${process.env.TELEGRAM_BOT_TOKEN}`;

/**
 * Telegram Bot Service
 * Sends growth reports, idea summaries, and notifications to users
 */

/**
 * Send a text message to a user
 */
export async function sendMessage(chatId, text, parseMode = 'HTML') {
  const url = `${TELEGRAM_API_BASE}/sendMessage`;
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      chat_id: chatId,
      text,
      parse_mode: parseMode,
    }),
  });

  if (!res.ok) {
    const err = await res.json();
    throw new Error(`Telegram API error: ${err.description}`);
  }

  return res.json();
}

/**
 * Send a formatted AI suggestion report to user
 */
export async function sendAIReport(chatId, suggestions) {
  let message = `🧠 <b>Growcial OS — AI Suggestions</b>\n\n`;

  suggestions.forEach((s, i) => {
    message += `<b>${i + 1}. ${s.title}</b>\n`;
    message += `${s.content}\n\n`;
  });

  message += `💡 <i>Generated by Growcial Intelligence Engine</i>`;

  return sendMessage(chatId, message);
}

/**
 * Send a daily growth summary
 */
export async function sendDailySummary(chatId, stats) {
  const message = `📊 <b>Daily Growth Report</b>

👥 Followers: <b>${stats.followers || '—'}</b>
❤️ Total Likes: <b>${stats.likes || 0}</b>
💬 Total Comments: <b>${stats.comments || 0}</b>
👁️ Total Views: <b>${stats.views || 0}</b>
📈 Engagement Rate: <b>${stats.engagementRate || '—'}%</b>

🔥 <i>Keep growing with Growcial OS!</i>`;

  return sendMessage(chatId, message);
}

/**
 * Send a notification when a post is ready
 */
export async function sendPostReady(chatId, postData) {
  const message = `🎬 <b>Your Post is Ready!</b>

📝 <b>Script:</b>
${postData.script || 'N/A'}

📌 <b>Caption:</b>
${postData.caption || 'N/A'}

#️⃣ <b>Hashtags:</b>
${postData.hashtags?.join(' ') || 'N/A'}

⏰ <b>Best Time to Post:</b> ${postData.bestTime || 'Now!'}

🚀 Go post and grow!`;

  return sendMessage(chatId, message);
}
